name: '⑇ ESlint'
author: 'Stefan Dej (meteyou)'
description: 'ESlint check'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules/
        key: mainsail-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
