name: PUSH

on:
    push:
        branches: [develop, master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
    group: ci-tests-${{ github.ref }}-PUSH
    cancel-in-progress: true

jobs:
    debs-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Debs-Cache
              uses: ./.github/actions/debs-cache/

    build:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Build
              uses: ./.github/actions/build/

    eslint:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: ESlint
              uses: ./.github/actions/eslint/

    prettier:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Prettier
              uses: ./.github/actions/prettier/

    test-cypress:
        needs: [debs-cache, build]
        runs-on: ubuntu-latest
        steps:
            - name: Cypress test
              uses: ./.github/actions/test-cypress/
